package codesignal.integercontainer;

import java.time.Duration;

import org.example.codesignal.integercontainer.IntegerContainer;
import org.example.codesignal.integercontainer.IntegerContainerImpl;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;

/**
 * The test class below can be considered as a playground - feel free to modify it as you need, e.g.:
 * - add your own custom tests
 * - delete existing tests
 * - modify test contents or expected output
 *
 * The results of tests from this file will always be at the beginning of the report generated by clicking the "Run" button.
 *
 * The results of these tests do not affect the final score (unless the project fails to build).
 */
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class SandboxTests {

    private IntegerContainer container;

    @BeforeEach
    void setUp() {
        container = new IntegerContainerImpl();
    }

    @Test
    @Order(1)
    void testSample() {
        Assertions.assertTimeoutPreemptively(Duration.ofMillis(200), () -> {
            Assertions.assertEquals(1, container.add(5));
            Assertions.assertEquals(2, container.add(10));
            Assertions.assertEquals(3, container.add(5));
            Assertions.assertTrue(container.delete(10));
            Assertions.assertFalse(container.delete(1));
            Assertions.assertEquals(3, container.add(1));
        });
    }
}
